### ISSUE TITLE
您好，请问网页版是否可以转成pdf呢

### ISSUE THREAD

**Issue by AlexShyXie** [Nagi-ovo/Cherno-CPP-Notes#1]
大佬您好，您这个笔记实在太棒了，我更喜欢离线阅读，然后还能做一些标记，感觉网页版的名字和目录都是中文，我希望能有一个pdf版本，可以吗

**Comment by Nagi-ovo** [comment]
之前有来着，obsidian导出的pdf格式有些问题还有些内容错误就在上线后删掉了。。。
我的建议是clone仓库后自己直接修改md文件内容，然后用obsidian这类笔记软件导出为pdf看😀

**Comment by AlexShyXie** [comment]
> 之前有来着，obsidian导出的pdf格式有些问题还有些内容错误就在上线后删掉了。。。
> 我的建议是clone仓库后自己直接修改md文件内容，然后用obsidian这类笔记软件导出为pdf看😀

好的，谢谢

**Comment by Nagi-ovo** [comment]
不客气，欢迎fork&pr！

**Comment by Nagi-ovo** [comment]
不客气～欢迎fork&pr！
此外，我找到了别人之前的fork，里面有当时的pdf文件：
https://github.com/MDZforever/Cherno-CPP-Notes

**Comment by Nagi-ovo** [comment]
有帮助的话可以给个⭐️，这个issue我就先关掉了～

**Comment by Nagi-ovo** [comment]
11.15.2023更新，已添加PDF文件。但最新的修正版还请见在线文档。
