### ISSUE TITLE
询问笔记软件

### ISSUE THREAD

**Issue by Willaaaaaaa** [Nagi-ovo/Cherno-CPP-Notes#4]
老师你好，你写的笔记真的是很赏心悦目、清晰明了。作为一个计科小白，我想问一下你这个pdf是用什么软件做出来。
我感觉是先用markdown记录，然后转成pdf的。但我会的markdown都是黑白灰，一点也不清晰明了，也没有你记得这么有色彩，能分享一下吗？如果你是用markdown的话能分享一个源文件让我学习一下吗？

**Comment by Nagi-ovo** [comment]
我是用的 Obsidian 笔记软件，完全本地且基于md语法，配置可以在谷歌和b站上找找，因为有一些css设置所以渲染出来确实会好看一些~

**Comment by Nagi-ovo** [comment]
btw推荐用cmake，qmake等构建工具来编译cpp🙂

**Comment by Willaaaaaaa** [comment]
好的老师！我现在只会用VS或vscode写简单的C++代码，你提到的cmake和qmake我也是只知道其名。我要学习的还很多，谢谢你的解答！🫡

**Comment by Nagi-ovo** [comment]
推荐多google & 问 ai（deepseekV2很好用，claude gpt什么的也当然可以），一起加油~
